Repository sun-zip/read-and-share, pull requests merged in 2025-03, with the labels that each got.

#38 Feat: 회원 정보 수정 기능 추가
  src/main/java/com/flab/readnshare/domain/member/controller/MemberApiController.java
  src/main/java/com/flab/readnshare/domain/member/dto/UpdateRequestDto.java
  src/main/java/com/flab/readnshare/domain/member/repository/MemberRepository.java
  src/main/java/com/flab/readnshare/domain/member/service/MemberService.java
Labels: 💫 feat

#42 feat: 특정 유저의 팔로우, 팔로잉 목록 조회 기능 추가
  src/main/java/com/flab/readnshare/domain/follow/controller/FollowApiController.java
  src/main/java/com/flab/readnshare/domain/follow/facade/FollowFacade.java
  src/main/java/com/flab/readnshare/domain/follow/repository/FollowRepository.java
  src/main/java/com/flab/readnshare/domain/follow/service/FollowService.java
  src/test/java/com/flab/readnshare/domain/follow/controller/FollowApiControllerTest.java
  src/test/java/com/flab/readnshare/domain/follow/facade/FollowFacadeTest.java
  src/test/java/com/flab/readnshare/domain/follow/repository/FollowRepositoryTest.java
  src/test/java/com/flab/readnshare/domain/follow/service/FollowServiceTest.java
Labels: 💫 feat

#32 docs: Book 도메인 관련 코드에 주석 설명 추가
  src/main/java/com/flab/readnshare/domain/book/controller/BookApiController.java
  src/main/java/com/flab/readnshare/domain/book/domain/Book.java
  src/main/java/com/flab/readnshare/domain/book/service/BookService.java
Labels: 📝 docs

#31 docs: Auth 도메인 관련 코드에 주석 설명 추가
  src/main/java/com/flab/readnshare/domain/auth/controller/AuthApiController.java
  src/main/java/com/flab/readnshare/domain/auth/domain/RefreshToken.java
  src/main/java/com/flab/readnshare/domain/auth/service/AuthService.java
  src/main/java/com/flab/readnshare/global/common/auth/jwt/JwtAuthInterceptor.java
  src/main/java/com/flab/readnshare/global/common/auth/jwt/JwtCode.java
  src/main/java/com/flab/readnshare/global/common/auth/jwt/JwtUtil.java
  src/main/java/com/flab/readnshare/global/common/resolver/SignInMember.java
  src/main/java/com/flab/readnshare/global/common/resolver/SignInMemberArgumentResolver.java
Labels: 📝 docs

#81 feat: 리프레쉬 토큰 로테이션 기능
  src/main/java/com/flab/readnshare/domain/auth/controller/AuthApiController.java
  src/main/java/com/flab/readnshare/domain/auth/service/AuthService.java
  src/test/java/com/flab/readnshare/domain/auth/service/AuthServiceTest.java
Labels: 💫 feat, ✅ test

#83 refactor: Auth 관련 에러코드 수정
  src/main/java/com/flab/readnshare/domain/auth/service/AuthService.java
  src/main/java/com/flab/readnshare/global/common/exception/AuthException.java
  src/main/java/com/flab/readnshare/global/common/exception/ErrorCode.java
Labels: ♻️ refactor

#98 feat: 멤버ID를 가져오는 커스텀 어노테이션 작성
  src/main/java/com/flab/readnshare/global/common/resolver/SignInMemberId.java
  src/main/java/com/flab/readnshare/global/common/resolver/SignInMemberIdArgumentResolver.java
  src/main/java/com/flab/readnshare/global/config/WebMvcConfig.java
Labels: 💫 feat

#119 feat: 파라미터 검증 예외 핸들러 추가
  src/main/java/com/flab/readnshare/global/common/advice/ApiExceptionAdvice.java
Labels: 💫 feat

#122 feat: 책 검색 페이징 기능 추가
  src/main/java/com/flab/readnshare/domain/book/controller/BookApiController.java
  src/main/java/com/flab/readnshare/domain/book/dto/SearchBookResponseDto.java
  src/main/java/com/flab/readnshare/domain/book/service/BookService.java
  src/test/java/com/flab/readnshare/domain/book/controller/BookApiControllerTest.java
  src/test/java/com/flab/readnshare/domain/book/service/BookServiceTest.java
Labels: 💫 feat, ✅ test

#167 refactor: 테스트 커버리지 보완 및 에러 리팩토링
  src/main/java/com/flab/readnshare/domain/member/domain/Member.java
  src/main/java/com/flab/readnshare/domain/member/dto/SignUpRequestDto.java
  src/main/java/com/flab/readnshare/global/config/WebMvcConfig.java
  src/test/java/com/flab/readnshare/domain/member/service/MemberServiceTest.java
Labels: ♻️ refactor, ✅ test

#172 refactor: Auth, Book, Favorite 도메인 테스트 커버리지 보완
  src/main/java/com/flab/readnshare/domain/auth/dto/SignInRequestDto.java
  src/main/java/com/flab/readnshare/domain/book/dto/SearchBookDetailResponseDto.java
  src/main/java/com/flab/readnshare/domain/book/dto/SearchBookResponseDto.java
  src/main/java/com/flab/readnshare/global/config/WebMvcConfig.java
  src/test/java/com/flab/readnshare/domain/auth/controller/AuthApiControllerTest.java
  src/test/java/com/flab/readnshare/domain/auth/service/AuthServiceTest.java
  src/test/java/com/flab/readnshare/domain/book/service/BookServiceTest.java
  src/test/java/com/flab/readnshare/domain/favorite/service/FavoriteBookServiceTest.java
Labels: ♻️ refactor, ✅ test
